### ISSUE TITLE
TypeScript: Missing types for `marked-terminal`

### ISSUE THREAD

**Issue by thejustinwalsh** [cameronhunter/ink-markdown#6]
When consuming this in a TypeScript project, I see that there is indeed a `devDependency` listed in the package.json  for marked-terminal, however, the types for this seem to export the type from marked-terminal, requiring an additional type install within the consuming project.

`npm i --save-dev @types/marked-terminal`

Although it is a bit of a boilerplate, would it be possible to define your own type that is compatible with the TerminalRendererOptions but does not require the additional types directly?

**Comment by cameronhunter** [comment]
I've added `@types/marked-terminal` to the `dependencies` list in `v1.0.4`. Thanks for opening the issue!
